baseURL = 'https://prapooskur.github.io'
languageCode = 'en-us'
title = 'Prasiddh Pooskur'
theme = 'hello-friend-ng'

publishDir = "docs"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Just a student."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "A simple personal site."
  keywords = "homepage, blog"
  images = [""]

  enableThemeToggle = true

  [params.footer]
    trademark = true
    rss = false
    copyright = true
    author = true

  # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/prapooskur"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/prapooskur"

  

[author]
  name = "Prasiddh Pooskur"


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Prasiddh Pooskur"
    subtitle = "A personal landing page"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd /home/Prasiddh"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu

  
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"

